version: '3.8'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: client
    stdin_open: true
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules